# Generated by Django 3.1.5 on 2021-02-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
